project:
  type: website
  output-dir: 'docs-tmp'

website:
  title: "Frederick Gathering of Eagles"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - activities.qmd
      - oral_histories.qmd
      - board.qmd
  margin-header: |
    ![](/images/GOE Logo_Final.png)

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
