project:
  type: website
  output-dir: 'docs'

website:
  title: "Frederick Gathering of Eagles"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - board.qmd
  margin-header: |
    ![](/images/Frederick GOE.png)

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true
