---
title: "Activities"
---

## Upcoming Activities

### September 13, 2025 @ 6:30 PM - Fall dance fling with instruction

Want to brush up on your dance step? Then why not plan to attend our Fall Dance on **Saturday, September 13** at [The Lodge Event Center at Homewood](https://maps.app.goo.gl/dkc4zmyBNqeuJXmz7) beginning at 6:30 PM! A dance instructor will be on hand to review and/or introduce the jitterbug, cha-cha, fox trot and waltz.

You can invite your children and grandchildren to attend, too. Dress is casual, and refreshments will be served. Try to bring a dance partner to the event. Some local Eagle Scouts will be invited. Call **Fred Broadrup** at (301) 606-1878 and leave a voice message with the number in your party if you'd like to attend.

If you enjoy this dance format, we can repeat the event during the year to add new dance steps and review prior ones.


## Past Activities

### May 8, 2025 @ 6:00 PM - Annual Dinner at Dutch's Daughter

The official yearly GOE celebration/recognition dinner will be at [Dutch's Daughter](https://maps.app.goo.gl/PepRyocW7NrqqNvAA), May 8.  Gathering time starts at 6:00 PM, a full dinner is provided, and it’s free (although donations to the GOE to support Scouting in Frederick County are welcomed and encouraged). We need to start getting a head count NOW so, if you plan to attend, please send us an email ASAP to [membership@frederickeagles.com](mailto:membership@frederickeagles.com). All Eagles are invited, whether they are members or not, but we particularly want to celebrate the achievement of those Scouts who received their Eagle rank this year. We have sent out an email to all Troop Scoutmasters and Committee Chairs to invite all Eagle youth, but if you are a member of a unit, you can help to spread the word and let them know about the dinner if they are interested.

### March 22, 2025 @ 6:30 PM - Happy Hour at Steinhardt

Soar into happy hour! 🦅 Join the Gathering of Eagles for drinks & camaraderie at [Steinhardt Brewing Company](https://maps.app.goo.gl/hw4dqd8unTngTFpn6) on March 22 at 6:30 PM.

### July 4, 2024 - Scouting in Baker Park

This is a great opportunity to at least see what Frederick County Scouting is doing.  If you want to help, please *contact us - need to figure out how to do this without exposing names and email addresses*.  If you just want to come down and see what is going on, that’s fine, too.

### May 29, 2024 - Annual Dinner at Dutch's Daughter

The official yearly GOE celebration/recognition dinner will be at Dutch's Daughter, May 29.  Gathering time starts at 6:00 PM, a full dinner is provided, and it’s free (although donations to the GOE to support Scouting in Frederick County are welcomed and encouraged).  We need to start getting a head count NOW so, if you plan to attend, please let us now ASAP.  All Eagles are invited, whether they are members or not, but we particularly want to celebrate the achievement of those Scouts who received their Eagle rank this year. We will be sending out an email to all Troop Scoutmasters and Committee Chairs to invite all Eagle youth, but if you are a member of a unit, you can help to spread the word and let them know about the dinner if they are interested.

### February 17, 2024 - Happy Hour at Attaboy Brewery

On February 17, we had a social gathering at the Attaboy Brewery in East Frederick.  We had 11 members attend, which was about 28% of our membership.  This was very successful and all who attended had a great time.
