---
title: "Frederick Gathering of Eagles"
---

The **Frederick County Gathering of Eagles** is a social organization celebrating all Eagle Scouts residing in the local Frederick County, MD. We welcome both adult and youth Eagles to join us for activities and networking opportunities. We encourage these Eagle Scouts to remain or become involved in the local Scouting district and promote the ideals of Scouting. 

The Gathering is a registered 501c3 non-profit; all contributions are tax-deductible. 

### Interested in learning more about becoming a member?

- All Eagle Scouts, of any age, living in Frederick County are eligible to join.
- You’ll enjoy a variety of social activities, potential volunteer matching, access to exclusive opportunities, and an invitation to our annual dinner. 
- Members are required to attend the annual dinner and/or make a donation to the organization and/or give their time to the local Scouting community. 
- FREE to become and stay a member. 

We hope you’ll consider joining our Gathering. Email [membership@frederickgoe.com](mailto:membership@frederickgoe.com) with questions.
